### ISSUE TITLE
Vouchers doesn't work

### ISSUE THREAD

**Issue by rafaht** [modpluz/xbilling-frontend#3]
Hi,
When I try to add a discount voucher at my order, I get a blank page.
I activated display_errors at php.ini and get this:
Fatal error: Call to undefined function voucherInfo() in /var/sentora/hostdata/zadmin/public_html/mydomain/xbilling/index.php on line 118

I tried to find this function in these files:
/etc/sentora/panel/modules/xbilling/code/webservice.ext.php
/xbilling/functions/xbilling.php
and don't find anything.
It's a bug?

**Comment by modpluz** [comment]
I'm pretty sure that function does exist.

However, I'll look into this

**Comment by rafaht** [comment]
Hi,
I'll wait for your check. I checked there and don't found this function.

**Comment by ccr1969** [comment]
all to undefined function voucherInfo() 
was this issue ever fixed and what was the fix as iam having same issue

**Comment by turknett** [comment]
I want to close off by mistake while giving off white page, please enter the coupon code when you help emergency
