### ISSUE TITLE
Cron accounts error

### ISSUE THREAD

**Issue by rafaht** [modpluz/xbilling-frontend#5]
Hi,
Because the xBilling isn't sending e-mails with the cron job created for accounts_jobs.php located in cron directory, I accessed this file from my browser and get this error:

array(4) { ["type"]=> int(2) ["message"]=> string(131) "fopen(http://panel.mydomain.com/api/xbilling): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error " ["file"]=> string(103) "/var/sentora/hostdata/zadmin/public_html/mydomain/xbilling/classes/xmwsclient.class.php" ["line"]=> int(112) } Problem reading data from http://panel.mydomain.com/api/xbilling

I changed my domain name to mydomain.
How to solve this? It's a bug?

**Comment by modpluz** [comment]
panel.mydomain.com should be the url to your control panel, please check that your "xBilling" settings are right.

**Comment by rafaht** [comment]
Yep, are right. I'm using the xBilling normally, only this archive have problem.
The settings are right.
