### ISSUE TITLE
Problem reading data with Sentora port change?

### ISSUE THREAD

**Issue by dlong93** [modpluz/xbilling-frontend#6]
So I setup the script and checked my php.ini and it all checks out but I am still getting this issue
Problem reading data from http://p2host.tk:1020/api/xbilling

I've went through the Sentora forums and it seems like I have things set up properly but what I am not seeing in a lot of the situations is people trying to use xbilling under a different port rather than 80? Would this actually make a difference or cause a problem?

**Comment by modpluz** [comment]
Please confirm that you have the file `/etc/sentora/panel/.htaccess`.
